{% set name = "slurmgen" %}
{% set version = "3.14.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slurmgen-{{ version }}.tar.gz
  sha256: 8d763783b181ac06fef4618d299bc996a2e367ebca2ea9b75ada424d7f267966

build:
  entry_points:
    - sgen = slurmgen:run_script
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.5
    - wheel >=0.45
    - setuptools-scm >=8.1
    - pip >=24.3
  run:
    - python >={{ python_min }}

test:
  imports:
    - slurmgen
  commands:
    - sgen --help
  requires:
    - python {{ python_min }}
    - pip >=24.3

about:
  summary: SlurmGen - Simple Manager for Slurm Jobs
  description: |
    SlurmGen is a very simple Slurm manager. The job description is stored 
    in JSON files. The JSON files are transformed into Slurm scripts. The 
    Slurm script can be run locally or on a Slurm Cluster. SlurmGen is not 
    a binding and/or a wrapper for Slurm. SlurmGen is only generating Slurm 
    scripts from JSON files. SlurmGen is written in Python without any 
    external dependencies.
  license: BSD-2-Clause
  license_file: LICENSE.txt
  doc_url: https://github.com/otvam/slurmgen
  dev_url: https://github.com/otvam/slurmgen
  home: https://github.com/otvam/slurmgen

extra:
  recipe-maintainers:
    - otvam
