{% set name = "slurmgen" %}
{% set version = "3.13.0" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slurmgen-{{ version }}.tar.gz
  sha256: 3d1887b7fa143ee4fd15850bdae0d0e914791e4cbdfbbb851e3befd8a4390d6e

build:
  entry_points:
    - sgen = slurmgen:run_script
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.2
    - wheel >=0.41
    - setuptools-scm >=7.1
    - pip >=24.2
  run:
    - python >={{ python_min }}

test:
  imports:
    - slurmgen
  commands:
    - sgen --help
  requires:
    - pip

about:
  summary: SlurmGen - Simple Slurm Manager
  description: |
    SlurmGen is a very simple Slurm manager. The job description is stored 
    in JSON files. The JSON files are transformed into Slurm scripts. The 
    Slurm script can be run locally or on a Slurm Cluster. SlurmGen is not 
    a binding and/or a wrapper for Slurm. SlurmGen is only generating Slurm 
    scripts from JSON files. SlurmGen is written in Python without any 
    external dependencies.
  license: BSD-2-Clause
  license_file: LICENSE.txt
  doc_url: https://github.com/otvam/slurmgen
  dev_url: https://github.com/otvam/slurmgen
  home: https://github.com/otvam/slurmgen

extra:
  recipe-maintainers:
    - otvam
