{% set name = "slurmgen" %}
{% set version = "3.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slurmgen-{{ version }}.tar.gz
  sha256: c1704dc4eda6f34ec11944165be05f7a70dfcd05c626e86730aabb3289e558f7

build:
  entry_points:
    - sgen = slurmgen:run_script
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >68.2
    - wheel >0.41
    - setuptools-scm >7.1
    - pip
  run:
    - python >=3.6

test:
  imports:
    - slurmgen
  commands:
    - sgen --help
  requires:
    - pip

about:
  summary: SlurmGen - Simple Slurm Manager
  description: |
    SlurmGen is a very simple Slurm manager. The job description is stored 
    in JSON files. The JSON files are transformed into Slurm scripts. The 
    Slurm script can be run locally or on a Slurm Cluster. SlurmGen is not 
    a binding and/or a wrapper for Slurm. SlurmGen is only generating Slurm 
    scripts from JSON files. SlurmGen is written in Python without any 
    external dependencies.
  license: BSD-2-Clause
  license_file: LICENSE.txt
  doc_url: https://github.com/otvam/slurmgen
  dev_url: https://github.com/otvam/slurmgen
  home: https://github.com/otvam/slurmgen

extra:
  recipe-maintainers:
    - otvam
